### ISSUE TITLE
💅 [Style]: PostProduct page style

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#111]
## Description
PostProduct page style

## To-do
- [x] PostProduct page route 생성
- [x] UploadImage 컴포넌트 생성 및 style
- [x] PostProduct page style

## ETC
20230616 - 202300613
