### ISSUE TITLE
🛠️ [Feature]: 프로필 페이지 기능 추가

### ISSUE THREAD

**Issue by oxxun21** [FRONTENDSCHOOL5/final-10-Goodi#119]
## Description
profile 컴포넌트로 내 프로필, 유저 프로필 재사용하며 프로필 내 필요 기능 연결

## To-do
- [ ] 내 프로필 정보 API 연동
- [ ] 내 프로필 수정 버튼 추가
- [ ] 내 프로필 수정 기능
- [ ] 다른 유저 프로필 정보 API 연동
- [ ] 팔로워, 팔로잉 API 연동
- [ ] 팔로워, 팔로잉 리스트 띄우기
- [ ] 해당 유저의 상품 목록 API 연결
- [ ] 해당 유저의 게시글 목록 API 연결 

## ETC
팔로우, 팔로우 취소 기능, 좋아요 기능도 있긴 함
