### ISSUE TITLE
🛠️ [Feature]: 나의 게시글 목록 API 연동

### ISSUE THREAD

**Issue by nkEllaaa** [FRONTENDSCHOOL5/final-10-Goodi#126]
## Description
게시글 관련 작업
나의 게시글 목록 API 연동
게시글 스타일 변경

## To-do
- [x] 게시글 UI 변경
- [x] 게시글 (나의 게시글 목록)API 연동 (페이지네이션 X)
- [x] 게시글 (게시글 작성) API 연동
- [x] postUI로부터 textarea에서 content 받기
- [x] postUI로부터 imageWrap에서 image 받기
- [x] 게시글 API 중 createdAt 데이터를 이용하여 생성된 후 경과된 시간으로 바꿔 표시
- [x] 좋아요 API 연동
- [x] 좋아요 취소 API 연동

## ETC
작업기간 : 20230617 -
