### ISSUE TITLE
💅 [Style]: Search modal style

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#152]
## Description
검색 기능 구현

## To-do
- [x] 네비게이션에서 버튼 누르면 검색 모달 나오기
- [x] 검색 스타일 
- [x] 검색결과가 있을떄, 없을때 조건부 스타일 생성
- [x] 최근 검색 기록이 있을떄 없을떄 조건부 스타일 생성

## ETC
230620 - 230620
