### ISSUE TITLE
👾 [Bug]: 프로필 페이지 수정 사항

### ISSUE THREAD

**Issue by oxxun21** [FRONTENDSCHOOL5/final-10-Goodi#155]
## Description
프로필 관련 이슈 정리

## To-do
- [x] 프로필 이미지 수정 후 새로고침 하면 풀림
- [x] 프로필 이미지 수정하지 않고 저장 누르면 이미지가 null이 됨
- [x] 값 변경 후 수정 취소 누르면 서버에는 안올라가지만 값이 바뀐 채 렌더링 됨
- [x] 팔로워, 팔로잉 삭제 후 카운트 바로 반영되지 않음
- [x] ProfileUI 클릭 시 유저 프로필로 이동
- [x] 내가 마이페이지가 아닌 내 유저 프로필로 넘어갈 수 있음
- [ ] 프로필 페이지 컴포넌트 재사용에 대해 -> 리팩토링으로 넘김
- [x] 팔로워, 팔로잉 작동 확인

## ETC
23.06.22 까지 수정
