### ISSUE TITLE
🛠️ [Feature]: Search page 기능구현

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#166]
## Description
search page 기능구현

## To-do
- [x] Search API 연결
- [x] 검색창에 입력한 값 버튼 누를시 API 쏘기
- [x] 받아온 값 result 페이지에 노출
- [x] Recoil로 검색기록 제어
- [x] 검색한 기록 최근 검색기록에 노출
- [x] 최근 검색기록 지우기
- [x] 로딩시 skeleton UI 사용

## ETC
20230621 - 20230621
