### ISSUE TITLE
💅 [Style]: main 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by oxxun21** [FRONTENDSCHOOL5/final-10-Goodi#2]
## Description
main 페이지 마크업 및 스타일링

## To-do
- [x] 작가 작품 나열
- [x] 카드 UI 리스트
- [x] 인기 작가 상품
- [x] 픽셀 -> 퍼센트 변환 
- [x] 마크업 리팩토링
- [x] css 리팩토링
- [x] 세부적인 부분 확인
- [x] 컴포넌트 분리

## ETC
기한: 20230605-20230608
