### ISSUE TITLE
🛠️ [Feature]: Chat 기능구현

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#226]
## Description
chat 간단한 기능 구현 
:chat API 서버가 없어 간단한 보여주기식 기능구현, 채팅 목록은 현재 팔로잉 기준

## To-do
- [x] 프로필, 팔로잉 API연결
- [x] 데이터를 불러오는 도중 스크레톤 UI 실행
- [x] 내가 클릭한 유저의 정보를 채팅창에 노출(유저가 보낸메시지, 유저의 이미지)
- [x] 인풋창에 메시지가 입력중일때만 보내기 버튼 활성화
- [x] 인풋창의 메시지를 전송하면 채팅창에 노출
- [x] 채팅 나가기를 누르면 현재 채팅중인 유저 채팅목록에서 제거

## ETC
20230624-20240625
