### ISSUE TITLE
♻️ [Refactor]: 웹접근성을 고려한 마크업 수정

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#272]
## Description
 시맨틱한 코드 수정 및 웹접근성을 고려하여 키보드 접근 수정

## To-do
- [ ] 폴더구조, 파일명 변경으로 인한 에러 수정
- [ ] 디테일페이지, 상품 업로드 , 상품 수정 마크업 수정 
- [ ] 프로필 페이지 마크업 수정
- [ ] 장바구니 페이지, 게시물 업로드, 게시물 마크업 수정

### 사용 검사도구 : LightHouse 웹접근성, HeadingsMap 
1. HeadingsMap 목차 정렬되어있는지
2. 사용자의 키보드 접근을 고려했는지
3. section, artice 태그들 목적에 맞게 잘 썼는지
