### ISSUE TITLE
♻️ [Refactor]: 웹 성능을 위한 이미지 최적화

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#279]
## Description
페이지 로딩시간을 줄이기고 웹 성능을 높이기 위해 이미지 최적화를 진행

## To-do
- [ ] 클라이언트가 업로드하는 이미지 압축
- [ ] 사이트 자체 제공 이미지 압축
- [ ] 이미지 크기를 정확히 지정하여 reflow 줄이기
- [ ] css sprite 기법 사용

## ETC
https://masankong.tistory.com/52
