### ISSUE TITLE
💅 [Style]: 로그인 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by nkEllaaa** [FRONTENDSCHOOL5/final-10-Goodi#3]
## Description
로그인 페이지 마크업, 스타일링 및 인풋 + 버튼 컴포넌트 

## To-do
- [x] 로그인 디폴트 페이지
- [x] 로그인 회원가입 페이지
- [x] 초기 유저 정보 설정 페이지
- [x] 인풋 컴포넌트
- [x] 버튼 컴포넌트
- [x] 캐러셀 기능구현

## ETC
기한: 20230605-20230608
