### ISSUE TITLE
💅 [Style]: layout component 마크업 및 스타일링

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#5]
## Description
header, footer, navigation 마크업및 스타일링

## To-do
- [x] 파일 생성및 문서 구조 수정
- [x] Header 마크업 및 스타일링
- [x] Navigation 마크업 및 스타일링
- [x] Footer 마크업 및 스타일링

## ETC
children 으로 컴포넌트 레이아웃 생성
