### ISSUE TITLE
💅 [Style]: 프로필 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by oxxun21** [FRONTENDSCHOOL5/final-10-Goodi#55]
## Description
유저 프로필 페이지 생성

## To-do
- [x] 이미지 리스트 위 작가 프로필 이슈 (main)
- [x] 가격 단위 처리 (main)
- [x] 페이지 레이아웃
- [x] 유저 프로필 마크업 및 스타일링
- [x] 게시물 컴포넌트 추가
- [x] 작가 상품 카드 UI 추가
- [x] 세부 사항 수정
- [x] main, profile 페이지 레이아웃 중복 요소 제거 (할 수 있을 거 같음)

## ETC
기한: 20230611 ~ 20230615
