### ISSUE TITLE
💅 [Style]: 로그인 페이지 세부 디자인 수정

### ISSUE THREAD

**Issue by nkEllaaa** [FRONTENDSCHOOL5/final-10-Goodi#57]
## Description
6/9 회의 안건에 따른 세부 디자인 수정 작업

## To-do
- [ ] 로그인 페이지 캐러셀 fade-in, fade-out 시간 조정
- [ ] 나만의 굿즈 판매 플랫폼 구디! 부분 폰트 사이즈 줄이기
- [ ] setprofile 페이지 전체 마진 수정
- [ ] setprofile image_def 및 add 버튼에 파일 추가 기능 
- [ ] mock 상품 수량 데이터 추가

## ETC
작업 기간 : 202306010 - 20230611
