### ISSUE TITLE
💅 [Style]: 상세페이지 디자인 이슈 수정

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#65]
## Description
상세페이지 디자인 이슈 수정

## To-do
- [x] 왼쪽 이미지 크기 수정
- [x] 상단 공통 배너 텍스트 대처
- [x] 디테일페이지 전체적임 탑 마진값 빼기
- [x] 작가 팔로우 버튼 조건부 설정하여

## ETC
기타사항
