### ISSUE TITLE
🛠️ [Feature]: 로그인 기능, 채팅 페이지 추가

### ISSUE THREAD

**Issue by oxxun21** [FRONTENDSCHOOL5/final-10-Goodi#85]
## Description
로그인, 프로필 기능 추가

## To-do
- [x] 로그인 기능 구현
- [x] 로그인 예외 처리
- [x] 로그인 예외 처리 스타일
- [x] 코드 리팩토링
- [x] 채팅 페이지 디자인
- [x] recoil을 통한 토큰 값 저장
