### ISSUE TITLE
🛠️ [Feature]: 회원가입 기능, API 연동

### ISSUE THREAD

**Issue by nkEllaaa** [FRONTENDSCHOOL5/final-10-Goodi#88]
## Description
회원가입 기능, API 연동

## To-do
- [x] accountName은 따로 input 받지 않고 email의 @ 앞까지로 처리 
- [x] join에서는 email, password를 받고 setprofile에 locate로 전달
- [x] setprofile에서 username을 받아 API 연결하여 오류처리
- [x] 정상 가입 시 버튼 눌렀을 때 setprofile 페이지로 이동
- [x] 벨리데이션에 따라 에러메세지 스타일링

## ETC
작업기간 : 20230615 - 20230616
