### ISSUE TITLE
💅 [Style]: 모달 레이아웃

### ISSUE THREAD

**Issue by nkEllaaa** [FRONTENDSCHOOL5/final-10-Goodi#90]
## Description
모달 컴포넌트 스타일링 및 기능

## To-do
- [x] 모달 컴포넌트 만들기 (버튼은 공통 컴포넌트 사용, 엑스버튼은 선택사항으로)
- [x] 메인에 적용
- [x] 예외처리 (엑스버튼, 뒷배경, 예-아니오)
- [x] 모달 띄워질 때 뒷배경 스크롤 방지

## ETC
작업기간 : 20230614 - 20230615
