### ISSUE TITLE
💅 [Style]: Navigation refactor

### ISSUE THREAD

**Issue by dananote** [FRONTENDSCHOOL5/final-10-Goodi#91]
## Description
Navigation refactor 스타일 리팩토링 및 상태에 따른 스타일 설정

## To-do
- [x] li 리스트 갯수에 맞게 map 돌리기
- [x] 각 버튼 페이지 연결
- [x] post 버튼 누를시 모달창 띄우기

## ETC
기타사항
